#!/bin/bash

#########################################################
################ DO NOT EDIT THIS FILE ##################
#########################################################

set -e

echo "Starting..."; echo;

JSON_FILE=${1:-$(tr -dc A-Za-z0-9 </dev/urandom | head -c 15).json}
echo "Date: $(date --utc)"
echo "Filename: $JSON_FILE"; echo;

echo "Testing AWS CLI version..."
aws --version || { echo "Error: The AWS CLI is not available."; exit 1; }

echo;
echo "Running scraper with filename $JSON_FILE..."
python -m scraper $JSON_FILE
echo "Scrape complete with final output $(pwd)/$JSON_FILE."

echo "Running tests"
test -e $JSON_FILE || { echo "Error: $JSON_FILE not found. You must output a file even when no data is available"; exit 1; }

test_output=$(python test_output.py $JSON_FILE)
echo "test output $test_output"
if [ "$test_output" != "OK" ]; then
  echo "Error: $JSON_FILE does not match schema. See errors above. Run `python test_output.py filename.json` to run test.";
  exit 1;
fi

echo "All tests finished"

echo;
echo "########################################"
echo "Summary"
echo "########################################"
echo "Lines: $(wc -l < ${JSON_FILE})"
echo "Bytes: $(wc -c < ${JSON_FILE})"
echo "Headers: $(head -n 1 ${JSON_FILE})"

echo;
echo "########################################"
echo "Sample: First 10 lines"
echo "########################################"
head -n 10 $JSON_FILE

echo;
echo "########################################"
echo "Sample: Last 10 lines"
echo "########################################"
tail -n 10 $JSON_FILE

echo;
echo "Complete."
